movie_bank = [
    {"title": "The Shawshank Redemption", "genre": "Drama", "release_year": 1994},
    {"title": "The Godfather", "genre": "Crime", "release_year": 1972},
    {"title": "The Dark Knight", "genre": "Action", "release_year": 2008},
    {"title": "Pulp Fiction", "genre": "Crime", "release_year": 1994},
    {"title": "Schindler's List", "genre": "Biography", "release_year": 1993},
    {"title": "The Lord of the Rings: The Return of the King", "genre": "Fantasy", "release_year": 2003},
    {"title": "Forrest Gump", "genre": "Drama", "release_year": 1994},
    {"title": "Inception", "genre": "Sci-Fi", "release_year": 2010},
    {"title": "Fight Club", "genre": "Drama", "release_year": 1999},
    {"title": "The Matrix", "genre": "Sci-Fi", "release_year": 1999},
    {"title": "Goodfellas", "genre": "Crime", "release_year": 1990},
    {"title": "The Empire Strikes Back", "genre": "Sci-Fi", "release_year": 1980},
    {"title": "Interstellar", "genre": "Sci-Fi", "release_year": 2014},
    {"title": "Spirited Away", "genre": "Animation", "release_year": 2001},
    {"title": "Saving Private Ryan", "genre": "War", "release_year": 1998},
    {"title": "The Silence of the Lambs", "genre": "Thriller", "release_year": 1991},
    {"title": "Se7en", "genre": "Thriller", "release_year": 1995},
    {"title": "The Usual Suspects", "genre": "Crime", "release_year": 1995},
    {"title": "The Lion King", "genre": "Animation", "release_year": 1994},
    {"title": "The Social Network", "genre": "Biography", "release_year": 2010},
    {"title": "The Shining", "genre": "Horror", "release_year": 1980},
    {"title": "The Departed", "genre": "Crime", "release_year": 2006},
    {"title": "Gladiator", "genre": "Action", "release_year": 2000},
    {"title": "Titanic", "genre": "Romance", "release_year": 1997},
    {"title": "Back to the Future", "genre": "Adventure", "release_year": 1985},
    {"title": "Braveheart", "genre": "Drama", "release_year": 1995},
    {"title": "Jurassic Park", "genre": "Sci-Fi", "release_year": 1993},
    {"title": "Casablanca", "genre": "Romance", "release_year": 1942},
    {"title": "The Prestige", "genre": "Drama", "release_year": 2006},
    {"title": "The Green Mile", "genre": "Drama", "release_year": 1999},
    {"title": "The Intouchables", "genre": "Comedy", "release_year": 2011},
    {"title": "City of God", "genre": "Crime", "release_year": 2002},
    {"title": "The Pianist", "genre": "Biography", "release_year": 2002},
    {"title": "Whiplash", "genre": "Drama", "release_year": 2014},
    {"title": "Terminator 2: Judgment Day", "genre": "Action", "release_year": 1991},
    {"title": "WALL-E", "genre": "Animation", "release_year": 2008},
    {"title": "The Wolf of Wall Street", "genre": "Biography", "release_year": 2013},
    {"title": "Mad Max: Fury Road", "genre": "Action", "release_year": 2015},
    {"title": "12 Angry Men", "genre": "Drama", "release_year": 1957},
    {"title": "The Great Gatsby", "genre": "Drama", "release_year": 2013},
    {"title": "Django Unchained", "genre": "Western", "release_year": 2012},
    {"title": "The Dark Knight Rises", "genre": "Action", "release_year": 2012},
    {"title": "Frozen", "genre": "Animation", "release_year": 2013},
    {"title": "A Clockwork Orange", "genre": "Drama", "release_year": 1971},
    {"title": "The Shape of Water", "genre": "Fantasy", "release_year": 2017},
    {"title": "The Exorcist", "genre": "Horror", "release_year": 1973},
    {"title": "The Revenant", "genre": "Adventure", "release_year": 2015},
    {"title": "The Breakfast Club", "genre": "Comedy", "release_year": 1985},
    {"title": "Psycho", "genre": "Thriller", "release_year": 1960},
    {"title": "The Hangover", "genre": "Comedy", "release_year": 2009},
    {"title": "Guardians of the Galaxy", "genre": "Action", "release_year": 2014},
    {"title": "The Fault in Our Stars", "genre": "Drama", "release_year": 2014},
    {"title": "The Notebook", "genre": "Romance", "release_year": 2004},
    {"title": "The Secret Life of Pets", "genre": "Animation", "release_year": 2016},
    {"title": "The Curious Case of Benjamin Button", "genre": "Drama", "release_year": 2008},
    {"title": "Moana", "genre": "Animation", "release_year": 2016},
    {"title": "Inside Out", "genre": "Animation", "release_year": 2015},
    {"title": "Coco", "genre": "Animation", "release_year": 2017},
    {"title": "Zootopia", "genre": "Animation", "release_year": 2016},
    {"title": "Big Hero 6", "genre": "Animation", "release_year": 2014},
    {"title": "Deadpool", "genre": "Action", "release_year": 2016},
    {"title": "The Incredibles", "genre": "Animation", "release_year": 2004},
    {"title": "The Lego Movie", "genre": "Animation", "release_year": 2014},
    {"title": "Finding Nemo", "genre": "Animation", "release_year": 2003},
    {"title": "Shrek", "genre": "Animation", "release_year": 2001},
    {"title": "Toy Story", "genre": "Animation", "release_year": 1995},
    {"title": "Jaws", "genre": "Thriller", "release_year": 1975},
    {"title": "Rocky", "genre": "Drama", "release_year": 1976},
    {"title": "Gladiator", "genre": "Action", "release_year": 2000},
    {"title": "Casino Royale", "genre": "Action", "release_year": 2006},
    {"title": "The Hunger Games", "genre": "Action", "release_year": 2012},
    {"title": "Avatar", "genre": "Sci-Fi", "release_year": 2009},
    {"title": "Eternal Sunshine of the Spotless Mind", "genre": "Romance", "release_year": 2004},
    {"title": "The Grand Budapest Hotel", "genre": "Comedy", "release_year": 2014},
    {"title": "The King's Speech", "genre": "Biography", "release_year": 2010},
    {"title": "The Social Network", "genre": "Biography", "release_year": 2010},
    {"title": "Birdman", "genre": "Drama", "release_year": 2014},
    {"title": "No Country for Old Men", "genre": "Crime", "release_year": 2007},
    {"title": "The Martian", "genre": "Sci-Fi", "release_year": 2015},
    {"title": "Spotlight", "genre": "Drama", "release_year": 2015},
    {"title": "Arrival", "genre": "Sci-Fi", "release_year": 2016},
    {"title": "The Shape of Water", "genre": "Fantasy", "release_year": 2017},
    {"title": "Her", "genre": "Romance", "release_year": 2013},
    {"title": "Once Upon a Time in Hollywood", "genre": "Drama", "release_year": 2019},
]